"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var index_1 = require("./storage/index");
exports.PostgreSQL = index_1.PostgreSQL;
exports.StorageType = index_1.StorageType;
exports.Storage = index_1.Storage;
exports.setupStorage = index_1.setup;
exports.RedisCache = index_1.RedisCache;
exports.RedisDataType = index_1.RedisDataType;
var postgresql_templete_account_1 = require("./templetes/postgresql_templete_account");
exports.PostgresTempleteAccount = postgresql_templete_account_1.TempleteAccount;
