"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var index_1 = require("./storage/index");
Object.defineProperty(exports, "PostgreSQL", { enumerable: true, get: function () { return index_1.PostgreSQL; } });
Object.defineProperty(exports, "StorageType", { enumerable: true, get: function () { return index_1.StorageType; } });
Object.defineProperty(exports, "Storage", { enumerable: true, get: function () { return index_1.Storage; } });
Object.defineProperty(exports, "setupStorage", { enumerable: true, get: function () { return index_1.setup; } });
Object.defineProperty(exports, "RedisCache", { enumerable: true, get: function () { return index_1.RedisCache; } });
Object.defineProperty(exports, "RedisDataType", { enumerable: true, get: function () { return index_1.RedisDataType; } });
var postgresql_templete_account_1 = require("./templetes/postgresql_templete_account");
Object.defineProperty(exports, "PostgresTempleteAccount", { enumerable: true, get: function () { return postgresql_templete_account_1.TempleteAccount; } });
