"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var index_1 = require("./storage/index");
exports.PostgreSQL = index_1.PostgreSQL;
var index_2 = require("./storage/index");
exports.StorageType = index_2.StorageType;
var index_3 = require("./storage/index");
exports.Storage = index_3.Storage;
var index_4 = require("./storage/index");
exports.setupStorage = index_4.setup;
var index_5 = require("./storage/index");
exports.RedisCache = index_5.RedisCache;
var index_6 = require("./storage/index");
exports.RedisDataType = index_6.RedisDataType;
var postgresql_templete_account_1 = require("./templetes/postgresql_templete_account");
exports.PostgresTempleteAccount = postgresql_templete_account_1.TempleteAccount;
